SCHEMA exppp_prob_func;

  FUNCTION exppp_colon_to_comma(
               lis: LIST [0:?] OF GENERIC:t
      ): ARRAY [1:5] OF GENERIC:t;

    LOCAL
      re  : ARRAY [1:5] OF GENERIC:t;
      res : ARRAY [1:5] OF GENERIC:t;
    END_LOCAL;
    re := [lis[1],5];  --the comma becomes a colon
    res := [lis[1]:5];
    RETURN(res);

  END_FUNCTION; -- exppp_colon_to_comma

END_SCHEMA; -- exppp_prob_func
