SCHEMA exppp_prob_func;

  FUNCTION exppp_colon_to_comma(
               lis: LIST [0:?] OF GENERIC:t
      ): ARRAY [1:5] OF GENERIC:t;

    LOCAL
      res : ARRAY [1:5] OF GENERIC:t;
    END_LOCAL;
    res := [lis[1]:5]; -- libexpress parser will accept this with the comma that exppp wants to use!
                       -- need to verify that it is not valid express with a comma (and if it is,
                       -- how does the meaning change?)
    RETURN(res);

  END_FUNCTION; -- exppp_colon_to_comma

END_SCHEMA; -- exppp_prob_func
