# This file was generated by fedex_python.  You probably don't want to edit
# it since your modifications will be lost if fedex_plus is used to
# regenerate it.
from SCL.SCLBase import *
from SCL.SimpleDataTypes import *
from SCL.ConstructedDataTypes import *
from SCL.AggregationDataTypes import *
from SCL.TypeChecker import check_type
from SCL.Expr import *
# ENUMERATION TYPE hair_color
hair_color = ENUMERATION([
	'bald',
	'red',
	])
# ENUMERATION TYPE favorite_color
favorite_color = ENUMERATION([
	'clear',
	'red',
	])
