# This file was generated by fedex_python.  You probably don't want to edit
# it since your modifications will be lost if fedex_plus is used to
# regenerate it.
import sys

from SCL.SCLBase import *
from SCL.SimpleDataTypes import *
from SCL.ConstructedDataTypes import *
from SCL.AggregationDataTypes import *
from SCL.TypeChecker import check_type
from SCL.Expr import *

schema_name = 'test_enums_same_name'

schema_scope = sys.modules[__name__]


# ENUMERATION TYPE hair_color
if (not 'bald' in globals().keys()):
	bald = EnumerationId()
else:
	print 'WARNING: redefined enum id'
if (not 'red' in globals().keys()):
	red = EnumerationId()
else:
	print 'WARNING: redefined enum id'
hair_color = ENUMERATION(
	bald,
	red,
	)

# ENUMERATION TYPE favorite_color
if (not 'clear' in globals().keys()):
	clear = EnumerationId()
else:
	print 'WARNING: redefined enum id'
if (not 'red' in globals().keys()):
	red = EnumerationId()
else:
	print 'WARNING: redefined enum id'
favorite_color = ENUMERATION(
	clear,
	red,
	)
