# This file was generated by fedex_python.  You probably don't want to edit
# it since your modifications will be lost if fedex_plus is used to
# regenerate it.
from SCL.SCLBase import *
from SCL.SimpleDataTypes import *
from SCL.ConstructedDataTypes import *
from SCL.AggregationDataTypes import *
from SCL.TypeChecker import check_type
from SCL.Expr import *
# ENUMERATION TYPE simple_datum_reference_modifier
simple_datum_reference_modifier = ENUMERATION([
	'line',
	'translation',
	])

####################
 # ENTITY line #
####################
class line(BaseEntityClass):
	'''Entity line definition.
	'''
	# This class does not define any attribute.
	pass
