cmake_minimum_required(VERSION 3.12)

set(run_a "${CMAKE_CURRENT_BINARY_DIR}/chunked_a")
set(run_b "${CMAKE_CURRENT_BINARY_DIR}/chunked_b")
file(REMOVE_RECURSE "${run_a}" "${run_b}")
file(MAKE_DIRECTORY "${run_a}" "${run_b}")

foreach(run "${run_a}" "${run_b}")
  execute_process(
    COMMAND "${EXE}" -k 2:1 "${INFILE}"
    WORKING_DIRECTORY "${run}"
    RESULT_VARIABLE result
  )
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "exp2cxx chunked generation failed")
  endif()
endforeach()

file(GLOB manifests_a "${run_a}/*.sources.cmake")
file(GLOB manifests_b "${run_b}/*.sources.cmake")
list(LENGTH manifests_a manifest_count_a)
list(LENGTH manifests_b manifest_count_b)
if(NOT manifest_count_a EQUAL 1 OR NOT manifest_count_b EQUAL 1)
  message(FATAL_ERROR "exp2cxx did not produce exactly one source manifest")
endif()
list(GET manifests_a 0 manifest_a)
list(GET manifests_b 0 manifest_b)
file(READ "${manifest_a}" manifest_text_a)
file(READ "${manifest_b}" manifest_text_b)
if(NOT manifest_text_a STREQUAL manifest_text_b)
  message(FATAL_ERROR "exp2cxx source manifests are not deterministic")
endif()

file(GLOB entity_chunks "${run_a}/*_unity_entities_[0-9][0-9][0-9][0-9].cc")
list(LENGTH entity_chunks entity_chunk_count)
if(entity_chunk_count LESS 2)
  message(FATAL_ERROR "fixture was not partitioned into multiple entity chunks")
endif()
foreach(chunk ${entity_chunks})
  file(READ "${chunk}" chunk_text)
  string(REGEX MATCHALL "#include \"entity/[^\"]+\"" entity_includes "${chunk_text}")
  list(LENGTH entity_includes include_count)
  if(include_count GREATER 2)
    message(FATAL_ERROR "generated chunk exceeds requested size: ${chunk}")
  endif()
endforeach()

file(GLOB type_chunks "${run_a}/*_unity_types_[0-9][0-9][0-9][0-9].cc")
list(LENGTH type_chunks type_chunk_count)
if(type_chunk_count LESS 2)
  message(FATAL_ERROR "fixture was not partitioned into multiple type chunks")
endif()
foreach(chunk ${type_chunks})
  file(READ "${chunk}" chunk_text)
  string(REGEX MATCHALL "#include \"type/[^\"]+\"" type_includes "${chunk_text}")
  list(LENGTH type_includes include_count)
  if(include_count GREATER 1)
    message(FATAL_ERROR "generated type chunk exceeds requested size: ${chunk}")
  endif()
endforeach()

string(REGEX MATCHALL "\"[^\"]+\\.cc\"" manifest_sources "${manifest_text_a}")
foreach(source ${manifest_sources})
  string(REPLACE "\"" "" source "${source}")
  if(NOT EXISTS "${run_a}/${source}")
    message(FATAL_ERROR "manifest names missing generated source: ${source}")
  endif()
endforeach()
