 # macros to be used in the CMakeLists generated by the schema scanner

# what args does this need?
MACRO( BUILD_SCHEMA )
  message( FATAL_ERROR "This macro has not been implemented yet." )
ENDMACRO( BUILD_SCHEMA )
